# This workflow will copy specific file to the other repo

# author KITAMURA Yui (at) Yui-Kitamura LLC.

name: CopyToOtherRepo

on:
  workflow_call:
    inputs:
      originalRepo:
        description: 'original repositories "owner/repoName" string value'
        required: true
        type: string
      originalBranch:
        description: 'original repositories branch name. If not specified, then use "main".'
        required: false
        type: string
      destRepo:
        description: 'copy destination repositories "owner/repoName" string value'
        required: true
        type: string
      destBranch:
        description: 'copy destination repositories branch name. If not specified, then use "main".'
        required: false
        type: string
      targetFilePath:
        description: 'copy target file path from project root in the repository. ex:"/target/myPj.jar"' 
        required: true
        type: string
    secrets:
      APP_ID:
        description: 'the app_id of your GitHubApp'
        required: true
      SECRET:
        description: 'the secret key of your GitHubApp'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: inputInit
      id: inVal
      run: |
        echo "orgRepo=${{input.originalRepo}}" >> $GITHUB_OUTPUT
        echo "orgBranch=${${{input.originalBranch}}:-'main'}" >> $GITHUB_OUTPUT
        echo "destRepo=${{input.destRepo}}" >> $GITHUB_OUTPUT
        echo "destBranch=${${{input.destBranch}}:-'main'}" >> $GITHUB_OUTPUT
        echo "tgtFile=${{input.targetFilePath}}" >> $GITHUB_OUTPUT
        if test ${{input.originalRepo}}${{input.originalBranch}} = ${{input.destRepo}}${{input.destBranch}}; then
          # if target and destination are the same, then exit with failure
          echo "status='failure'" >> $GITHUB_OUTPUT
        fi

    - name: Get github token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.SECRET }}

    - name: checkOutOrigin
      uses: actions/checkout@v3
      with:
        repository: ${{ inVal.outputs.orgRepo }}
        ref: ${{ inVal.outputs.orgBranch }}
    - name: git setting
      run: |
        git config --local user.email "copyToOtherRepo.yml@workflow.github.yui.eng.pro"
        git config --local user.name "GitHub Action"

    - name: check file exist
      run: |
        targetFileFullPath=$GITHUB_WORKSPACE${{inVal.outputs.tgtFile}}
        if test -f "$targetFileFullPath"; then
          : #checkOk
        else
          # if file not exist, then exit workflow with failure status
          echo "status='failure'" >> $GITHUB_OUTPUT
        fi

    - name: checkout destination
      uses: actions/checkout@v3
      with:
        repository: ${{ inVal.outputs.destRepo }}
        ref: ${{ inVal.outputs.destBranch }}

