# This workflow will test the workflow "CopyToOtherRepo"

# author KITAMURA Yui (at) Yui-Kitamura LLC.

name: CopyToOtherRepoTest

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: Yui-KitamuraLLC/workflows/.github/workflows/copyToOtherRepo.yml@main
    secrets:
      app_id: ${{secrets.APP_ID}}
      secret: ${{secrets.SECRET}}