# This workflow will test the workflow "CopyToOtherRepo"

# author KITAMURA Yui (at) Yui-Kitamura LLC.

name: CopyToOtherRepoTest

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    needs: getEnv
    uses: Yui-KitamuraLLC/workflows/.github/workflows/CopyToOtherRepo.yml@${{github.ref_name}}