# This workflow will build a Java project with Maven,
# then commit the .jar file to the branche

# author KITAMURA Yui (at) Yui-Kitamura LLC.

name: Java_Build_Maven_And_Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setPushSha
      id: pushSha
      if: ${{github.event_name == 'push' }}
      run: echo 'TARGET_SHA=' ${{ github.sha }} >> $GITHUB_ENV
    - name: setPRSha
      id: prSha
      if: ${{github.event_name == 'pull_request' }}
      run: echo 'TARGET_SHA=' ${{ github.event.pull_request.head.sha }} >> $GITHUB_ENV
    - name: shaShow
      id: targetSha
      run: echo "SHA=${{ env.TARGET_SHA }}" >> $GITHUB_OUTPUT
    - run: echo ${{steps.targetSha.outputs.SHA}}

    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: mavenBuild
      run: mvn -B package --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v2.0.1
      
    - uses: actions/upload-artifact@v3
      id: upload
      with:
        name: 'Package'
        path: target/*.jar

    outputs:
      targetSha: ${{ steps.targetSha.outputs.SHA }}

  attachComment:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: actions/checkout@v3

    - name: download-build
      id: download
      uses: actions/download-artifact@v3
      with:
        name: 'Package'
        path: target

    - name: echo-dl-path
      run: ls -R
      working-directory: ${{steps.download.outputs.download-path}}

    - name: jarName
      id: jarName
      run: |
        find ${{steps.download.outputs.download-path}} -name *.jar -not -name original*
        jar_name=$(find ${{steps.download.outputs.download-path}} -name *.jar -not -name original*)
        echo "jarName=${jar_name}" >> $GITHUB_OUTPUT

    - name: git setting
      run: |
        git config --local user.email "mavenBuildCommit.yml@workflow.github.yui.eng.pro"
        git config --local user.name "GitHub Action"

    - name: Commit files
      id: commit
      run: |
        git add ${{steps.jarName.outputs.jarName}}
        git commit -m "build jar file by GitHubAction(maven.yml)" -a
        git push
        echo "sha=$(git show --format='%H' --no-patch)" >> $GITHUB_OUTPUT

    - name: create-commit-comment-orgCmt
      uses: peter-evans/commit-comment@v2
      with:
        sha: ${{ needs.build.outputs.targetSha }}
        body: |
          build generated jar file on ${{ steps.commit.outputs.sha }}
          - Created by [commit-comment](https://github.com/marketplace/actions/commit-comment)
          
    - name: create-commit-comment-jarCmt
      uses: peter-evans/commit-comment@v2
      with:
        sha: ${{ steps.commit.outputs.sha }}
        body: |
          build generated jar file on ${{ needs.build.outputs.targetSha }}
          - Created by [commit-comment](https://github.com/marketplace/actions/commit-comment)
